name: build
run-name: Gatsby Contentful Build and Deploy
on:
  workflow_call:
    secrets:
      ACTIONS_DEPLOY_KEY:
        description: GitHub Deploy Key
      CONTENTFUL_SPACE_ID:
        description: 'Contentful Space ID passed from the build-on-publish.yml workflow'
        required: true
      CONTENTFUL_ACCESS_TOKEN:
        description: 'Contentful Access Token passed from the build-on-publish.yml workflow'
        required: true
      CONTENTFUL_ENVIRONMENT:
        description: 'Contentful environment'
        required: true
      OSHWA_BEARER_TOKEN:
        description: 'OSHWA api key'
        required: true
        
  push:
    branches: [ main ]
env:
  ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
  CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
  CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
  CONTENTFUL_ENVIRONMENT: ${{ secrets.CONTENTFUL_ENVIRONMENT }}
  OSHWA_BEARER_TOKEN: ${{ secrets.OSHWA_BEARER_TOKEN }}
jobs:
  pull-build-deploy:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [18.9.0]
    steps:
      - uses: actions/checkout@v4
      - name: Update Main Branch
        run: git pull origin main
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Build
        run: npm run gh-build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public